DROP TABLE IF EXISTS swimswam_user;

CREATE TABLE swimswam_user (
    user_id SERIAL PRIMARY KEY,
    public_user_id INT UNIQUE NOT NULL,
    username VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(50) NOT NULL UNIQUE,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    admin BOOLEAN DEFAULT FALSE
);